name: OutMCN
options:
  bundleIdPrefix: com.outmcn
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    TARGETED_DEVICE_FAMILY: "1"
    CODE_SIGNING_ALLOWED: "NO"
    CODE_SIGN_IDENTITY: ""
    DEVELOPMENT_TEAM: ""
    ENABLE_BITCODE: "NO"
targets:
  OutMCN:
    type: application
    platform: iOS
    sources:
      - path: OutMCN
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.outmcn.tools
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: OutMCN/Info.plist
      properties:
        CFBundleDisplayName: OutMCN
        CFBundleShortVersionString: "1.8.4"
        CFBundleVersion: "18"
        UILaunchScreen:
          UIColorName: LaunchBackground
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false